### ISSUE TITLE
(1) Cannot create new project [0]

### ISSUE THREAD

**Issue by asymeon** [AuthEceSoftEng/cenote-api#24]
Still getting a 500 error

**Comment by johnantonn** [comment]
Should this be closed? @iamnapo @MichaelPap  @asymeon

**Comment by iamnapo** [comment]
I'm not sure. I personally tried with multiple accounts and cannot replicate it.

**Comment by johnantonn** [comment]
Closing this since the issue did not persist and it could not be reproduced..
